### ISSUE TITLE
channel-playback-monkeys fails if call into the application is less than length of tt-monkeys

### ISSUE THREAD

**Issue by dougbtv** [asterisk/ari-examples#15]
Is there a way to update this demo application so that it doen't fail if the calling party hangs up before tt-monkeys stops playing?

I've got my example of how to easily crash it here: https://gist.github.com/dougbtv/bef8c442f47c432147ffd9c511d435ca

My thinking is... The default way that someone handles being greeted by a prompt -- is naturally to hang up during them! :)

**Comment by samuelg** [comment]
That's because the example throws for the purposes of demonstration. In a production application it would not make sense to throw for such an error. We typically log these cases in case the error is important, but it's usually best to make your application resilient to such errors.

**Comment by dougbtv** [comment]
@samuelg -- it's not being thrown by this application proper -- it's being throw elsewhere in the libraries, by swagger it appears. let me brew up another example...

Note how in the example where I would think it would throw the error on purpose -- it is not. I have a `console.log("this is never displayed")` in here, that is... never displayed.


```
 doug   originate  ~  codebase  vnf-asterisk-controller  cat check.js 
/*jshint node: true*/
'use strict';

var ari = require('ari-client');
var util = require('util');

ari.connect('http://172.19.0.3:8088', 'asterisk', 'asterisk', clientLoaded);

// handler for client being loaded
function clientLoaded (err, client) {
  if (err) {
    throw err;
  }

  // handler for StasisStart event
  function stasisStart(event, channel) {
    console.log(util.format(
          'Monkeys! Attack %s!', channel.name));

    var playback = client.Playback();
    channel.play({media: 'sound:tt-monkeys'},
                  playback, function(err, newPlayback) {
      if (err) {
        console.log("THIS IS NEVER DISPLAYED");
        throw err;
      }
    });
    playback.on('PlaybackFinished', playbackFinished);

    function playbackFinished(event, completedPlayback) {
      console.log(util.format(
          'Monkeys successfully vanquished %s; hanging them up',
          channel.name));
      channel.hangup(function(err) {
        if (err) {
          throw err;
        }
      });
    }
  }

  // handler for StasisEnd event
  function stasisEnd(event, channel) {
    console.log(util.format(
          'Channel %s just left our application', channel.name));
  }

  client.on('StasisStart', stasisStart);
  client.on('StasisEnd', stasisEnd);

  client.start('inbound');
}
 doug   originate  ~  codebase  vnf-asterisk-controller  node check.js 
[ 'This API is using a deprecated version of Swagger!  Please see http://github.com/wordnik/swagger-core/wiki for more info' ]
Monkeys! Attack Local/123@inbound-00000011;2!
Monkeys successfully vanquished Local/123@inbound-00000011;2; hanging them up
Channel Local/123@inbound-00000011;2 just left our application
/home/doug/codebase/vnf-asterisk-controller/node_modules/ari-client/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

Error: {"message":"Channel not found"}
    at SwaggerRequest.swaggerError [as errorCallback] (/home/doug/codebase/vnf-asterisk-controller/node_modules/ari-client/lib/resources.js:944:19)
    at Object.error (/home/doug/codebase/vnf-asterisk-controller/node_modules/swagger-client/lib/swagger.js:1077:24)
    at EventEmitter.error (/home/doug/codebase/vnf-asterisk-controller/node_modules/swagger-client/lib/swagger.js:1296:19)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at emit (/home/doug/codebase/vnf-asterisk-controller/node_modules/shred/lib/shred/request.js:454:21)
    at /home/doug/codebase/vnf-asterisk-controller/node_modules/shred/lib/shred/request.js:473:9
    at setBodyAndFinish (/home/doug/codebase/vnf-asterisk-controller/node_modules/shred/lib/shred/response.js:103:7)
    at IncomingMessage.<anonymous> (/home/doug/codebase/vnf-asterisk-controller/node_modules/shred/lib/shred/response.js:120:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by dougbtv** [comment]
Facepalm -- I'm looking at the wrong error handler. Thanks for the eyeballs @samuelg -- appreciate it

```
function playbackFinished(event, completedPlayback) {
      console.log(util.format(
          'Monkeys successfully vanquished %s; hanging them up',
          channel.name));
      channel.hangup(function(err) {
        if (err) {
          console.log("THIS is the error that I shouldn't throw!");
          throw err;
        }
      });
```

**Comment by samuelg** [comment]
No worries.
